name: WeCom Daily Reminder

on:
  schedule:
    - cron: '28 07 * * *' # 07:28 UTC = 14:28 (2:28 PM) Vietnam time
  workflow_dispatch: # Cho phép chạy thủ công

jobs:
  send_reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Send reminder to WeCom
        run: |
          curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=aff7c878-2dad-4c74-b439-943c75b5a8cb' \
          -H 'Content-Type: application/json' \
          -d '{
                "msgtype": "text",
                "text": {
                  "content": "không gì là khó"
                }
              }'

