name: WeCom Daily Reminder

on:
  schedule:
    - cron: '25 07 * * *' # 07:25 UTC = 14:25 (2:25 PM) Vietnam time
  workflow_dispatch: # Cho phÃ©p cháº¡y thá»§ cÃ´ng

jobs:
  send_reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Send reminder to WeCom
        run: |
          curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=aff7c878-2dad-4c74-b439-943c75b5a8cb' \
          -H 'Content-Type: application/json' \
          -d '{
                "msgtype": "text",
                "text": {
                  "content": " auto auto ðŸŽ‰"
                }
              }'
